//! ExamSafe desktop app.
//!
//! Layering: `ui/*.slint` is presentation only; [`controller`] drives the pure state machine from
//! `examsafe-core` and executes its effects through `examsafe-platform` adapters.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod controller;
mod sample_plan;
mod tray;

use std::process::ExitCode;
use std::sync::Arc;
use std::time::Instant;

use examsafe_platform::helper_client::{HelperClient, LaunchMode};
use examsafe_platform::store::FileExamModeStore;
use slint::ComponentHandle;

use crate::controller::Controller;

/// Code generated by slint-build from `ui/`. It is not ours, so our lints don't apply to it.
#[allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]
mod ui {
    slint::include_modules!();
}
use ui::{AppWindow, Phase, PlanItem, StepItem};

fn main() -> ExitCode {
    let started = Instant::now();
    match run(started) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("examsafe: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run(started: Instant) -> Result<(), Box<dyn std::error::Error>> {
    let ui = AppWindow::new()?;

    // EXAMSAFE_NO_ELEVATE=1 skips the UAC prompt while developing the UI.
    let mode = if std::env::var_os("EXAMSAFE_NO_ELEVATE").is_some() {
        LaunchMode::Direct
    } else {
        LaunchMode::Elevated
    };
    let executor = Arc::new(HelperClient::next_to_current_exe(mode)?);
    let store = Box::new(FileExamModeStore::in_app_data());
    let tray = tray::Tray::create()?;

    let controller = Controller::new(&ui, store, executor, tray);
    controller::install(&controller);
    controller.start();

    ui.show()?;
    eprintln!(
        "examsafe: window shown after {} ms",
        started.elapsed().as_millis()
    );

    // Closing the window only hides it; the tray keeps the app reachable until "Quit"
    // or "Close ExamSafe".
    slint::run_event_loop_until_quit()?;
    Ok(())
}
